// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package queries

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertDriftAnalysisProject = `-- name: UpsertDriftAnalysisProject :batchexec
INSERT INTO drift_analysis_project (drift_analysis_run_id, dir, type, drifted, succeeded, init_output, plan_output, skipped_due_to_pr, resources_added, resources_changed, resources_destroyed)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (drift_analysis_run_id, dir) DO UPDATE
SET type                = EXCLUDED.type,
    drifted             = EXCLUDED.drifted,
    succeeded           = EXCLUDED.succeeded,
    init_output         = EXCLUDED.init_output,
    plan_output         = EXCLUDED.plan_output,
    skipped_due_to_pr   = EXCLUDED.skipped_due_to_pr,
    resources_added     = EXCLUDED.resources_added,
    resources_changed   = EXCLUDED.resources_changed,
    resources_destroyed = EXCLUDED.resources_destroyed
`

type UpsertDriftAnalysisProjectBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertDriftAnalysisProjectParams struct {
	DriftAnalysisRunID uuid.UUID
	Dir                string
	Type               string
	Drifted            bool
	Succeeded          bool
	InitOutput         *string
	PlanOutput         *string
	SkippedDueToPr     bool
	ResourcesAdded     *int32
	ResourcesChanged   *int32
	ResourcesDestroyed *int32
}

// Shared write path for the progress ticks and the terminal ingest. Keyed on the unique index
// (drift_analysis_run_id, dir), so re-sending a project updates it in place instead of duplicating.
func (q *Queries) UpsertDriftAnalysisProject(ctx context.Context, arg []UpsertDriftAnalysisProjectParams) *UpsertDriftAnalysisProjectBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.DriftAnalysisRunID,
			a.Dir,
			a.Type,
			a.Drifted,
			a.Succeeded,
			a.InitOutput,
			a.PlanOutput,
			a.SkippedDueToPr,
			a.ResourcesAdded,
			a.ResourcesChanged,
			a.ResourcesDestroyed,
		}
		batch.Queue(upsertDriftAnalysisProject, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertDriftAnalysisProjectBatchResults{br, len(arg), false}
}

func (b *UpsertDriftAnalysisProjectBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertDriftAnalysisProjectBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
