// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package queries

import (
	"context"
)

// iteratorForCreateDriftAnalysisProjectsBatch implements pgx.CopyFromSource.
type iteratorForCreateDriftAnalysisProjectsBatch struct {
	rows                 []CreateDriftAnalysisProjectsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateDriftAnalysisProjectsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateDriftAnalysisProjectsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].DriftAnalysisRunID,
		r.rows[0].Dir,
		r.rows[0].Type,
		r.rows[0].Drifted,
		r.rows[0].Succeeded,
		r.rows[0].InitOutput,
		r.rows[0].PlanOutput,
		r.rows[0].SkippedDueToPr,
	}, nil
}

func (r iteratorForCreateDriftAnalysisProjectsBatch) Err() error {
	return nil
}

func (q *Queries) CreateDriftAnalysisProjectsBatch(ctx context.Context, arg []CreateDriftAnalysisProjectsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"drift_analysis_project"}, []string{"drift_analysis_run_id", "dir", "type", "drifted", "succeeded", "init_output", "plan_output", "skipped_due_to_pr"}, &iteratorForCreateDriftAnalysisProjectsBatch{rows: arg})
}
