// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: git_repository.sql

package queries

import (
	"context"
)

const findGitRepositoryById = `-- name: FindGitRepositoryById :one
SELECT id, organization_id, name, analysis_token
FROM git_repository
WHERE id = $1
`

func (q *Queries) FindGitRepositoryById(ctx context.Context, id int64) (GitRepository, error) {
	row := q.db.QueryRow(ctx, findGitRepositoryById, id)
	var i GitRepository
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.AnalysisToken,
	)
	return i, err
}
