// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"time"
)

type GitOrganization struct {
	ID             int64
	Provider       string
	ProviderID     string
	Name           string
	InstallationID *int64
}

type GitRepository struct {
	ID             int64
	OrganizationID int64
	Name           string
	AnalysisToken  string
}

type SyncStatusUser struct {
	ID       int64
	UserID   int64
	SyncedAt time.Time
	Attempts int32
}

type User struct {
	ID                    int64
	Provider              string
	ProviderID            string
	Name                  string
	Username              string
	Email                 string
	AccessToken           string
	AccessTokenExpiresAt  *time.Time
	RefreshToken          string
	RefreshTokenExpiresAt *time.Time
}

type UserGitOrganization struct {
	ID                int64
	UserID            int64
	GitOrganizationID int64
	Role              string
}
