// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"time"

	"github.com/google/uuid"
)

type DriftAnalysisProject struct {
	ID                 int64
	DriftAnalysisRunID uuid.UUID
	Dir                string
	Type               string
	Drifted            bool
	Succeeded          bool
	InitOutput         *string
	PlanOutput         *string
}

type DriftAnalysisRun struct {
	Uuid                   uuid.UUID
	RepositoryID           int64
	TotalProjects          int32
	TotalProjectsDrifted   int32
	AnalysisDurationMillis int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type GitOrganization struct {
	ID             int64
	Provider       string
	ProviderID     string
	Name           string
	AvatarUrl      *string
	InstallationID *int64
}

type GitRepository struct {
	ID             int64
	OrganizationID int64
	ProviderID     string
	Name           string
	IsPrivate      bool
	AnalysisToken  *string
}

type SyncStatusUser struct {
	ID       int64
	UserID   int64
	SyncedAt time.Time
	NextSync time.Time
	Attempts int32
}

type User struct {
	ID                    int64
	Provider              string
	ProviderID            string
	Name                  string
	Username              string
	Email                 string
	AccessToken           string
	AccessTokenExpiresAt  *time.Time
	RefreshToken          string
	RefreshTokenExpiresAt *time.Time
}

type UserGitOrganization struct {
	ID                int64
	UserID            int64
	GitOrganizationID int64
	Role              string
}
