// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_org.sql

package queries

import (
	"context"
)

const claimOnePendingSyncOrg = `-- name: ClaimOnePendingSyncOrg :one
UPDATE git_organization_sync
SET next_sync = NOW() + INTERVAL '5 minutes'
WHERE organization_id = (SELECT git_organization_sync.organization_id
                         FROM git_organization_sync
                         WHERE git_organization_sync.next_sync < NOW()
                         FOR UPDATE SKIP LOCKED
                         LIMIT 1)
RETURNING id, organization_id, synced_at, next_sync
`

// ClaimOnePendingSyncOrg atomically selects and claims one due row. The short next_sync
// bump is a failure backoff: on success the loop calls UpdateGitOrganizationSyncStatus,
// which sets the real +1 day schedule.
func (q *Queries) ClaimOnePendingSyncOrg(ctx context.Context) (GitOrganizationSync, error) {
	row := q.db.QueryRow(ctx, claimOnePendingSyncOrg)
	var i GitOrganizationSync
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SyncedAt,
		&i.NextSync,
	)
	return i, err
}

const createGitOrganizationSyncIfNotExists = `-- name: CreateGitOrganizationSyncIfNotExists :exec
INSERT INTO git_organization_sync (organization_id, next_sync)
VALUES ($1, NOW())
ON CONFLICT (organization_id) DO NOTHING
`

func (q *Queries) CreateGitOrganizationSyncIfNotExists(ctx context.Context, organizationID int64) error {
	_, err := q.db.Exec(ctx, createGitOrganizationSyncIfNotExists, organizationID)
	return err
}

const updateGitOrganizationSyncStatus = `-- name: UpdateGitOrganizationSyncStatus :one
UPDATE git_organization_sync
SET synced_at = NOW(),
    next_sync = NOW() + INTERVAL '1 day'
WHERE organization_id = $1
RETURNING id, organization_id, synced_at, next_sync
`

func (q *Queries) UpdateGitOrganizationSyncStatus(ctx context.Context, organizationID int64) (GitOrganizationSync, error) {
	row := q.db.QueryRow(ctx, updateGitOrganizationSyncStatus, organizationID)
	var i GitOrganizationSync
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SyncedAt,
		&i.NextSync,
	)
	return i, err
}
